version: '3'
services:
  
  #-------------------------------------------------------------------------
  # SERVICIO SERVIDOR WEB (Prestashop)
  #-------------------------------------------------------------------------
  web:
    # IMAGEN USADA
    image: bitnami/prestashop
    # NOMBRE QUE LE VOY A DAR AL CONTENEDOR
    container_name: web
    environment:
      PRESTASHOP_DATABASE_USER: juanma
      PRESTASHOP_DATABASE_PASSWORD: jmcg
      PRESTASHOP_DATABASE_NAME: prestashop
      PRESTASHOP_DATABASE_HOST: datos
    # REDIRECCIÓN DE PUERTOS
    ports:
      - 80:80     
    # SERVICIOS QUE TIENEN QUE ARRANCAR ANTES DE ARRANCAR ESTE
    depends_on:
     - datos
    # REDES A USAR
    networks:
      - ejemplo
    
  
  #--------------------------------------------------
  # SERVICIO SERVIDOR DE BASE DE DATOS MARIADB
  #--------------------------------------------------

  # NOMBRE DEL SERVICIO
  datos:
    # IMAGEN USADA
    image: mariadb
    # NOMBRE QUE LE VOY A DAR AL CONTENEDOR
    container_name: bd
    # LISTA DE VALORES DE ENTORNO CON SUS VALORES
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prestashop
      MYSQL_USER: juanma
      MYSQL_PASSWORD: jmcg
    # REDIRECCIÓN DE PUERTOS
    #ports:
    #  - 3316:3306
    # VOLÚMENES A USAR POR EL CONTENEDOR
    volumes:
      # DOCKER VOLUME
     - "./basedatos:/var/lib/mysql"
    # REDES A USAR
    networks:
      - ejemplo

# DEFINICIÓN DE VOLÚMENES DOCKER A USAR POR LOS SERVICIOS (OPCIONAL)
volumes:
  data:
    # TIPO DE DRIVER
    driver: local

# DEFINICIÓN DE LAS REDES A USAR POR LOS SERVICIOS (OPCIONAL)
networks:
  # NOMBRE DE LA RED
  ejemplo:
    # DRIVER DE LA RED
    driver: bridge